---
## Selinux

selinux_enabled: true

## Zabbix
zabbix_repo_url: http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
zabbix_server: prd-zabbix01-lim.int.beemovil.com,prd-zabbix01-lim.beemovil.com
zabbix_active_server: prd-zabbix01-lim.int.beemovil.com
zabbix_url: http://prd-zabbix01-lim.int.beemovil.com/zabbix
zabbix_user: Admin
zabbix_pass: b33m0v1l
zabbix_client_host: "{{ ansible_hostname | upper }}"
zabbix_client_ip: "{{ ansible_eth0.ipv4.address }}"
zabbix_client_groups: ""
zabbix_client_templates: ""
zabbix_proxy: ""
zabbix_client_status: disabled
zabbix_client_rule_iptables_add: true

## Iptables 
iptables_rules:
  zabbix:
    table: filter
    jump: ACCEPT
    chain: IN_public_allow
    ctstate: NEW
    destination_port: 10050
    protocol: tcp
    state: present
