---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: zabbix

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Blox.yml
  when: ansible_os_family == 'Blox'

- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Copy Zabbix-agent main configuration
  template: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent
  tags:
    - zabbix

- name: zabbix-agent service state
  service: name=zabbix-agent state=started enabled=yes
  tags:
    - zabbix

- include: register_client.yml

- include: iptables.yml
  when: ansible_os_family == 'RedHat'
