---
- name: Install Repo | Zabbix
  apt: deb=http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.2-1+xenial_all.deb
  tags:
    - zabbix

- name: Install Agent | Zabbix
  apt: name=zabbix-agent state=present update_cache=yes
  tags:
    - zabbix
